# Generated by Django 5.2.1 on 2025-06-18 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Level', '0001_initial'),
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('day_of_lecture', models.CharField(max_length=20)),
                ('start_lecture', models.TimeField()),
                ('end_lecture', models.TimeField()),
                ('day_of_section', models.CharField(max_length=20)),
                ('start_section', models.TimeField()),
                ('end_section', models.TimeField()),
                ('instructor_lecture', models.CharField(max_length=100)),
                ('instructor_section', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='classroom.classroom')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='Level.level')),
            ],
        ),
    ]
